```{r}

library('mirt')
library('dplyr')
library('knitr')

```


```{r}
<<<<<<< HEAD
data <- read.csv("sampleData.csv", header=TRUE) 

print(data)

# 
# for (c in colnames(data)) {
# #    print(attributes(data[[c]]))
# #    print(table(data[[c]], exclude = NULL))
#   data[[c]]<- as.factor(data[[c]])
#   }
# 
# str(data)
=======
data <- read.csv("baseData.csv", header=TRUE) 
>>>>>>> main

# print(data)

<<<<<<< HEAD

# dt <- table(data$Q2A)
# dt
# chisq <- chisq.test(dt)
# chisq

=======
data<- data[c('Q1A', 'Q3A', 'Q4A', 'Q5A', 'Q6A', 'Q7A', 'Q8A', 'Q9A', 'Q14A', 'Q21A')]
print(data)
>>>>>>> main
# scale <-(data[,1:6])

mod1 <- (mirt(data, 1, verbose = FALSE, itemtype = "graded", SE = TRUE))
mod1


<<<<<<< HEAD
M2(mod1, type = "C2", calcNULL = FALSE, CI=.95)
=======
mod1

M2(mod1, type = "C2", calcNULL = FALSE)
>>>>>>> main


```



```{r}
# A second area of of interest is to assess how well each item fits the model.
itemfit(mod1)

```




```{r}
summary(mod1)
```

```{r}
plot(mod1, type='trace', which.item = c(1,2,3,4,5,6), facet_items=T, 
     as.table = TRUE, auto.key=list(points=F, lines=T, columns=4, space = 'top', cex = .8), 
              theta_lim = c(-3, 3), 
     main = "")

```

```{r}
plot(mod1, type='infotrace', which.item = c(1,2,3,4,5,6), facet_items=T, 
     as.table = TRUE, auto.key=list(points=F, lines=T, columns=1, space = 'right', cex = .8), 
              theta_lim = c(-3, 3), 
     main="")


```
